from contextvars import ContextVar

_language_index = ContextVar("_language_index", default = 0)

def set_lang(index: int):
    _language_index.set(index)

def get_lang() -> int:
    return _language_index.get()
translations = {
    'chinese': ['Chinese', 'ភាសាចិន', '中文'],
    'username': ['Username', 'ឈ្មោះ​អ្នកប្រើប្រាស់', '用户名'],
    'password': ['Password', 'ពាក្យសម្ងាត់', '密码'],
    'success': ['Success', 'ជោគជ័យ', '成功'],
    'fail': ['Fail', 'បរាជ័យ', '失败'],
    'enter_username_pass': ['Enter username and password', 'បញ្ចូលឈ្មោះអ្នកប្រើប្រាស់ និងពាក្យសម្ងាត់', '输入用户名和密码'],
    'enter_user': ['Enter username', 'បញ្ចូលឈ្មោះអ្នកប្រើ', '输入用户名'],
    'enter_password': ['Enter password', 'បញ្ចូលពាក្យសម្ងាត់', '输入密码'],
    'invalid_username': ['Invalid username', 'ឈ្មោះ​អ្នកប្រើប្រាស់​មិន​ត្រឹមត្រូវ', '无效的用户名'],
    'username_exists': ['Username already exists', 'ឈ្មោះ​អ្នកប្រើប្រាស់​មានរួចហើយ', '用户名已存在'],
    'email_exists': ['Email already exists', 'អ៊ីមែលមានរួចហើយ', '电子邮件已存在'],
    'server_error': ['Server error', 'កំហុសម៉ាស៊ីនមេ', '服务器错误'],
    'invalid_user_password': ['Invalid username or password', 'ឈ្មោះអ្នកប្រើ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ', '用户名或密码无效'],
    'invalid_password': ['Invalid password', 'ពាក្យសម្ងាត់មិនត្រឹមត្រូវ', '无效的密码'],
    'account_disabled': ['Account disabled', 'គណនី​ត្រូវ​បាន​បិទ', '帐户已禁用'],
    'account_blocked': ['Account blocked', 'គណនីត្រូវបានរារាំង', '帐户被封锁'],
    'invalid_parameters': ['Invalid parameters', 'ប៉ារ៉ាម៉ែត្រ​មិន​ត្រឹមត្រូវ', '无效参数'],
    'invalid_token': ['Invalid token', 'សញ្ញា​សម្ងាត់​មិន​ត្រឹមត្រូវ', '令牌无效'],
    'id_not_found': ['ID not found!', 'រកមិនឃើញអត្តសញ្ញាណប័ណ្ណ!', '未找到身份证！'],
    'user_not_found': ['User not found!', 'រកមិនឃើញអ្នកប្រើប្រាស់!', '未找到用户！'],
    "app_token_required": ['App token is required!', 'ត្រូវការសញ្ញា​សម្ងាត់កម្មវិធី!', '需要应用令牌！'],
    'name_not_found': ['Name not found!', 'រកមិនឃើញឈ្មោះទេ។', '未找到名称'],
    'product_not_found': ['Product not found!', 'រកមិនឃើញផលិតផល!', '未找到产品！'],
    'merchant_not_found': ['Merchant not found!', 'រកមិនឃើញឈ្មួញ!', '未找到商家！'],
    'record_not_found': ['Record not found!', 'រកមិនឃើញកំណត់ត្រា!', '找不到记录！'],
    'unautherized_access': ['Unautherized access to this route', 'គ្មានការអនុញ្ញាតចូលប្រើ', '未经授权访问此路由'],
    'invalid_status_id': ['Invalid status ID!', 'លេខសម្គាល់ស្ថានភាពមិនត្រឹមត្រូវ!', '状态 ID 无效！'],
    'data_cannot_empty': ['Data cannot empty!', 'ទិន្នន័យមិនអាចទទេបានទេ!', '数据不能为空！'],
    'rate_limit_exceeded': ['Rate limit exceeded!', 'លើសដែនកំណត់អត្រា!', '超过限速!'],
    'request_timed_out': ['Request timed out!', 'សំណើអស់ពេលហើយ!', '请求超时!'],
    'invalid_api_key': ['Invalid api key!', 'សោ api មិនត្រឹមត្រូវ!', '无效的 API 密钥！'],
    'invalid_filter_by': ['Invalid filter By', 'តម្រង​មិន​ត្រឹមត្រូវ', '无效的过滤依据'],
    'invalid_format': ['Invalid format', 'ទម្រង់មិនត្រឹមត្រូវ', '無效的格式'],
    'invalid_date_format': ['Invalid date format', 'ទម្រង់មិនត្រឹមត្រូវ', '無效的格式'],
    'cant_update_more_than_one': ['Cannot update more than one', 'មិនអាចអាប់ដេតលើសពីមួយបានទេ', '无法更新多个'],
    'end_date_cannot_small_than_start_date': ['End date cannot small than start date', 'កាលបរិច្ឆេទបញ្ចប់មិនអាចតូចជាងកាលបរិច្ឆេទចាប់ផ្តើមទេ', '结束日期不能小于开始日期'],
    'invalid_shift_type': ['Invalid shift type', 'វេនធ្វើការមិនត្រឹមត្រូវ', '班次类型无效'],
    'annual_leave_balance_empty': ['Your annual leave balance is empty.', 'សមតុល្យការឈប់សម្រាកប្រចាំឆ្នាំរបស់អ្នកគឺអស់ហើយ', '您的年假余额为零'],
    'cannot_apply_leave_last_next_year': ['Cannot apply leave previous year or next year', 'មិនអាចអនុវត្តការឈប់សម្រាកពីឆ្នាំមុន ឬឆ្នាំក្រោយបានទេ', '不能申请去年或明年的假期'],
    'invalid_leave_qty_format': ['Invalid leave qty format', 'ទម្រង់សមតុល្យការឈប់សម្រាកប្រចាំឆ្នាំមិនត្រឹមត្រូវ', '年假余额无效'],
    'date_not_leave_qty': ['Leave qty not match with your date take leave', 'ចំនួនច្បាស់មិនត្រូវគ្នានឹងកាលបរិច្ឆេទឈប់សម្រាករបស់អ្នក', '请假数量与请假日期不符'],
    'already_apply_leave_today': ['You already apply leave full day','អ្នកបានស្នើសុំការឈប់សម្រាកនៅថ្ងៃនេះរួចហើយ', '您今天已经申请休假了'],
    'already_apply_morning': ['You already apply leave morning shift','អ្នកបានអនុវត្តការឈប់សម្រាកពេលព្រឹករួចហើយ', '您已申请离开早班'],
    'already_apply_afternoon': ['You already apply leave afternoon shift','អ្នកបានអនុវត្តការឈប់សម្រាកពេលរសៀលរួចហើយ', '您已申请离开下午班'],
    'cannot_leave_more_than_1_day': ['You cannot take leave more than 1 per day','អ្នកមិនអាចឈប់សម្រាកលើសពី 1 ក្នុងមួយថ្ងៃបានទេ។', '每天休假不得超过 1 天'],
    'not_handle_job_staff': ['You are not a staff who handle job','អ្នកមិនមែនជាបុគ្គលិកដែលទទួលការងារនោះទេ', '你不是处理工作的员工'],
    'not_sup': ['You are not supervisor','អ្នកមិនមែនជាអ្នកគ្រប់គ្រងទេ', '你不是主管'],
    'not_hod': ['You are not HOD','អ្នកមិនមែនជាប្រធានផ្នែកទេ', '你不是部门主管'],
    'invalid_hand_over_staff': ['Invalid hand over job user','ឈ្មោះអ្នកទទួលការងារមិនត្រឹមត្រូវ', '无效移交作业用户'],
    'invalid_sup_user': ['Invalid supervisor user','ឈ្មោះអ្នកគ្រប់គ្រងមិនត្រឹមត្រូវ', '无效的主管用户'],
    'invalid_hod_user': ['Invalid hod user','ឈ្មោះអ្នកhodមិនត្រឹមត្រូវ', '无效的 hod 用户'],
    'hand_over_remark_required': ['Hand over remark is required','អ្នកទទួលការងារត្រូវ​តែមាន​', '必须注明交接'],
    'sup_remark_required': ['Sup remark is required','អ្នកគ្រប់គ្រងត្រូវ​តែមាន​', '需要主管备注'],
    'hod_remark_required': ['HOD remark is required','ប្រធានផ្នែកត្រូវ​តែមាន​', 'HOD 备注为必填项'],
    'cannot_apply_leave_due_to': ['Cannot apply leave due to ','មិនអាចដាក់ច្បាប់ឈប់សម្រាកដោយសារ​', '无法申请休假，原因是'],
    'double_deduct': ['Double deduct leave','ការឈប់សម្រាកគុណថ្វេរដង​', '双倍扣除假期'],
    'leave_is_empty': ['Your leave is empty!','ការឈប់សម្រាករបស់អ្នកគឺគ្មានតុល្យភាព!​', '您的休假没有余额！'],
    'already_apply_that_day': ['Already that day!','Already that day!​', 'Already that day!'],
    'already_apply_haft_day': ['Already apply haft day!','Already apply haft day!​', 'Already apply haft day!'],
    'cannot_apply_bigger_than_total': ['Cannot apply leave bigger than total leave','មិនអាចឈប់សម្រាកច្រើនជាងការឈប់សម្រាកសរុបបានទេ', '申請的休假不能超過休假總額'],
    'record_exist': ['Record already have​', 'Record already have'],
    'cannot_leave_more_than_half_year_limit': ['Your leave reach to limit for haft year!​', 'Your leave reach to limit for haft year!'],
    'leave_dates_blocked': ['Not allow to take leave!​', 'Not allow to take leave!'],
    'invalid_rule_input': ['Invalid rule format. Use commas and numbers only.', 'ទម្រង់ច្បាប់មិនត្រឹមត្រូវ។ ប្រើលេខជាមួយសញ្ញក្បៀស (,)', '规则格式无效。只能使用逗号和数字'],
    'invalid_rule_id': ['Rule does not exist.', 'ច្បាប់មិនមានទេ។', '规则不存在。'],
    'permission_group_not_found': ['Permission group not found!', 'រកមិនឃើញការអនុញ្ញាត!', '未找到权限组！'],
    'permission_rule_not_found': ['Permission rule not found!', 'រកមិនឃើញច្បាប់អនុញ្ញាត!', '未找到权限规则！'],
    'invalid_rule_name': ['Invalid rule name', 'ឈ្មោះច្បាប់មិនត្រឹមត្រូវ', '规则名称无效'],
    'employee_has_no_permission': ['Employee has no permission.', 'បុគ្គលិកគ្មានសិទ្ធិទេ។', '员工没有权限。'],
    'department_not_found': ['Department not found!', 'រកមិនឃើញផ្នែក!', '未找到部门！'],
    'position_not_found': ['Position not found!', 'រកមិនឃើញមុខតំណែង!', '未找到职位！'],
    'service_grade_not_found': ['Service grade not found!', 'រកមិនឃើញកម្រិតសេវា!', '未找到服务等级！'],
    'employee_not_found': ['Employee not found!', 'រកមិនឃើញបុគ្គលិក!', '未找到员工！'],
    'company_code_not_found': ['Company code not found!', 'រកមិនឃើញកូដក្រុមហ៊ុន!', '未找到公司代码！'],
    'plan_not_found': ['Plan not found!', 'រកមិនឃើញផែនការ!', '未找到计划！'],
    'only_pdf_and_image_file_are__allowed':['Only PDF and image files are allowed.',' អនុញ្ញាតតែឯកសារ PDF និងរូបភាពប៉ុណ្ណោះ។',',只允许上传 PDF 和图片文件。'],
    'user_limit_reached':['User limit reached.','បានឈានដល់ចំនួនអ្នកប្រើអតិបរមា។','已达到用户上限'],
    'company_not_found': ['Company not found!', 'រកមិនឃើញក្រុមហ៊ុន!', '未找到公司！'],
    'branch_not_found': ['Branch not found!', 'រកមិនឃើញសាខា!', '未找到分支！'],
    'fail_to_fetch_companies': ['Failed to fetch companies', 'បរាជ័យក្នុងការទាញយកក្រុមហ៊ុន', '获取公司失败'],
    'company_already_exists': ['Company already exists', 'ក្រុមហ៊ុនមានរួចហើយ', '公司已存在'],
    'cannot_delete_active_group':['Cannot delete an active group.','មិនអាចលុបក្រុមដែលកំពុងសកម្មបានទេ។','无法删除正在使用的群组。'],
    'group_have_employee':['The group has employees.','ក្រុមនេះមានបុគ្គលិក។','该群组中有员工。'],
    'admin_not_found': ['Admin not found', 'រកមិនឃើញអ្នកគ្រប់គ្រងទេ', '未找到管理员'],
    'inactive_rule_id': ['Inactive rule ID', 'លេខសម្គាល់ច្បាប់មិនសកម្ម', '非活动规则 ID'],
    'no_permission_groups_found': ['No permission groups found', 'រកមិនឃើញក្រុមអនុញ្ញាតទេ', '未找到权限组'],
    'rule_not_allowed': ['Rule not allowed', 'ច្បាប់មិនអនុញ្ញាត', '不允许的规则'],
    'unautherized_access_to_group': ['No permission for this group', 'គ្មានការអនុញ្ញាតចូលប្រើ', '未经授权访问此路由'],

}

def get_translation(key: str) -> str:
    index = get_lang()
    return translations.get(key, [''])[index]