name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 110.74.222.231
          username: root
          password: 12345
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            pwd
            ls
            docker ps